services:
  postgres:
    image: ghcr.io/identicum/postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"

  keycloak:
    image: ghcr.io/identicum/keycloak:25.0
    container_name: keycloak
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: postgres
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - "./keycloak-custom-authenticator/target/keycloak-lab-authenticator-1.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-lab-authenticator-1.0-SNAPSHOT.jar"
      - "./keycloak-rest-repo/target/keycloak-lab-repo-1.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-lab-repo-1.0.0-SNAPSHOT.jar"
      - "./sherpa-theme/target/sherpa-theme.jar:/opt/keycloak/themes/sherpa/"
      
# keycloak2:
#   image: ghcr.io/identicum/keycloak:25.0
#   container_name: keycloak2
#   depends_on:
#     - postgres
#   environment:
#     KEYCLOAK_ADMIN: admin
#     KEYCLOAK_ADMIN_PASSWORD: admin
#     KC_DB: postgres
#     KC_DB_USERNAME: keycloak
#     KC_DB_PASSWORD: keycloak
#     KC_DB_URL_HOST: postgres
#   command: start-dev
#   ports:
#     - "8081:8080"
#
# proxy:
#   image: ghcr.io/identicum/nginx:latest
#   container_name: proxy
#   volumes:
#     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#   ports:
#     - "80:80"
#   depends_on:
#     - keycloak
#     - keycloak2

  sherpa:
    container_name: sherpa
    image: ghcr.io/identicum/sherpa-deploy:latest
    pull_policy: always
    ports:
      - "9000:9000"
    volumes:
      - "./terraform:/terraform"
    working_dir: /terraform
    command: "python apply-config.py"
    depends_on:
      - keycloak

#  proxy:
#    image: ghcr.io/identicum/nginx:latest
#    container_name: proxy
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "80:80"
#
#  web1:
#    image: ghcr.io/identicum/nginx:latest
#    container_name: web1
#    volumes:
#      - ./web1:/usr/share/nginx/html
#    ports:
#      - "8081:80"
#
#  web2:
#    image: ghcr.io/identicum/nginx:latest
#    container_name: web2
#    volumes:
#      - ./web2:/usr/share/nginx/html
#    ports:
#      - "8082:80"
#
#  web3:
#    image: ghcr.io/identicum/nginx:latest
#    container_name: web3
#    volumes:
#      - ./web3:/usr/share/nginx/html
#    ports:
#      - "8083:80"

  mmock:
    image: jordimartin/mmock
    container_name: mmock
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./mocks/config:/config

volumes:
  postgres_data:
