services:
  postgres:
    image: ghcr.io/identicum/postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"

  keycloak:
    image: ghcr.io/identicum/keycloak:25.0
    container_name: keycloak
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: postgres
    command: start-dev
    ports:
      - "8080:8080"

  sherpa:
    container_name: sherpa
    image: ghcr.io/identicum/sherpa-deploy:latest
    pull_policy: always
    ports:
      - "9000:9000"
    volumes:
    - "C:/Users/nahue/mi-app-docker/terraform:/terraform"
    working_dir: /terraform
    command: "python apply-config.py"
