request:
  method: POST
  path: /auth
  body: "{\"email\": \"test@id.com\",\"password\": \"123\"}"
response:
  statusCode: 200
  headers:
    Content-Type: 
      - "application/json"
  body: >
    {
    "email": "test@id.com",
    "password": "123"
    }